services:
  project-name-frontend:
    image: gitlab.tazonte.rw:5050/tazonte/project-name/frontend/main:latest
    container_name: project-name-frontend-dev
    ports:
      - ${PORT}:3000
    restart: always
