export const API_TAG_TYPES = [
    "GET_PRODUCT_ENTRIES",
    "GET_ORDER_REQUESTS",
    "GET_OFFERS",
    "GET_SINGLE_ENTRY",
    "GET_SINGLE_ORDER_REQUEST",
    "GET_ORDERS",
    "GET_SINGLE_ORDER",
    "GET_SINGLE_ENTRY_REVIEWS",
]
