export const COLOR_CONFIG = {
	"project-name-gray": "#798A97",
	"project-name-dark-gray": "#354753",
	"project-name-light-gray": "#BAC7D1",
	"project-name-white": "#F1F7FB",
	"project-name-primary": "#FFB229",
	"project-name-blue": "#0E638C",
	"project-name-green": "#51B349",
	"project-name-green-faded": "#51b3493d",
	"project-name-yellow": "#DC8400",
	"project-name-dark-white": "#DEE7EE",
	"project-name-primary-faded": "#ffb2293d",
	"project-name-light-green": "#51B34929",
	"project-name-red": "#CF593F",
	"project-name-red-faded": "#cf593f29",
	"project-name-dark-blue": "#0B415B",
	"project-name-black": "#000000",
	"project-name-pure-white": "#FFFFFF",
} as const;
